name: tubes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  google_fonts: ^6.1.0
  flutter_svg_provider: ^1.0.7
  intl: ^0.19.0
  qr_flutter: ^4.0.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  flutter_pdfview: ^1.0.4
  path_provider: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  table_calendar: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/img/Logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/Berita1.png
    - assets/img/Berita2.png
    - assets/img/Berita3.png
    - assets/img/Berita4.png
    - assets/img/Berita5.png
    - assets/img/Logo.png
    - assets/img/Hospital.png
    - assets/img/Ambulance.png
    - assets/img/Konsultasi.png
    - assets/img/dokter/
    - assets/img/photo_profile.png
    - assets/img/pembayaran/DANA.png
    - assets/img/pembayaran/dana.jpg
    - assets/img/pembayaran/Ovo.png
    - assets/img/pembayaran/ovo.jpg
    - assets/img/pembayaran/LinkAja.png
    - assets/img/pembayaran/Shopee_pay.png
    - assets/img/pembayaran/Gopay.png